.TH APTURL 8 "September 01, 2008"

.SH NAME
apturl \- graphical apt\-protocol interpreting package installer

.SH SYNOPSIS
\fBapturl\fP [\fBoptions...\fP] <\fBURL\fP>

.SH DESCRIPTION
\fBapturl\fP is a simple graphical application that takes an URL (following the
apt\-protocol) as a command line option, parses it and carries out the
operations that the URL describes (that is, it asks the user if he wants the
indicated packages to be installed and if the answer is positive does so).

.SH USAGE
\fBapturl\fP just needs an URL conforming with the apt-protocol in order to
work. Additionally, it recognizes the following options:
.TP
\fB\-p, \-\-http\-proxy\fP
Use the given HTTP proxy in order to download the packages.

.SH EXAMPLES
.TP
apturl apt:pidgin,pidgin-plugin-pack
Installs Pidgin and Pidgin Plugin Pack (if the user confirms).
.TP
apturl apt:freevial?section=universe
Enables the "universe" component and installs package Freevial.
.TP
apturl apt:adobe-flashplugin?channel=lucid-partner
Enables the "partner" repository and installs package adobe-flashplugin.
Available repositories are listed in /usr/share/app-install/channels/.
.TP
apturl apt+http://launchpad.net/~mvo/ppa?package=2vcard
Installs 2vcard from the indicated PPA (if the user confirms), and afterward
asks if the PPA should be removed again or it should remain enabled.
.br
Warning: This is currently disabled because of security concerns.

.SH EXIT CODES
.TP
0
All requested packages have been successfully installed or were already
installed.
.TP
1
The user aborted the installation of one or more packages.
.TP
2
There was an error doing the requested operations, or the user aborted the
installation while Synaptic (and not apturl itself) was working.
.TP
3
The arguments with which \fBapturl\fP was called were incorrect (e.g., it
was called without any argument or the given URL was wrong).

.SH BUGS
Please report any bug on https://bugs.launchpad.net/ubuntu/+source/apturl.

.SH SEE ALSO
\fBsynaptic\fR

.SH AUTHORS
\fBapturl\fP was written by Michael Vogt <michael.vogt@ubuntu.com> for
Canonical, Ltd. and this manual page by Siegfried-A. Gevatter
<rainct@ubuntu.com>.
.PP
It is released under the GNU General Public License, version 2 or any
later version published by the Free Software Foundation.
